name: speed_breaker_alert
description: Offline speed breaker alert app

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^10.1.0
  sensors_plus: ^4.0.2
  flutter_tts: ^3.8.5
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  flutter_background_service: ^5.0.5
  wakelock_plus: ^1.1.4
  csv: ^5.0.2

flutter:
  uses-material-design: true
